YANBE/Controllers/InstallController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Mvc.Filters;
using System.Web.Security;
using Core.Domain;
using Core.Library;
using EFConvention;
using Microsoft.Ajax.Utilities;
using YANBE.Library.Filters;
using YANBE.Models;

namespace YANBE.Controllers
{
    [InstallationOnly]
    public class InstallController : Controller
    {
        public InstallController()
        {
            
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Settings()
        {
            var configuration = WebConfigurationManager.OpenWebConfiguration("~");
            var section = (ConnectionStringsSection)configuration.GetSection("connectionStrings");
            var model = new SettingsModel()
            {
                ConnectionString = section.ConnectionStrings["DefaultConnection"].ConnectionString
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Settings(SettingsModel model)
        {
            if (ModelState.IsValid)
            {
                var configuration = WebConfigurationManager.OpenWebConfiguration("~");
                var section = (ConnectionStringsSection)configuration.GetSection("connectionStrings");
                section.ConnectionStrings["DefaultConnection"].ConnectionString = model.ConnectionString;
                configuration.Save();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult CreateAccount()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult CreateAccount(AccountModels.RegisterModel model)
        {
            var context = DependencyResolver.Current.GetService<DbContext>();
            if (ModelState.IsValid)
            {
                var user = new User()
                {
                    Name = model.Username,
                    Password = Hash.CreateHash(model.Password),
                    Email = model.Email
                };
                context.Set<User>().Add(user);
                context.SaveChanges();
                FormsAuthentication.SetAuthCookie(model.Username, true);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

YANBE/Views/Install/CreateAccount.cshtml
@model YANBE.Models.AccountModels.RegisterModel

@{
    ViewBag.Title = "Register";
}

@using (Html.BeginForm("CreateAccount", "Install", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

YANBE/Views/Install/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Install YANBE";
}


<div class="row">
    <div class="col-md-8">
        <h2>Install YANBE</h2>
        <ol>
            <li>@Html.ActionLink("Configure installation", "Settings", "Install")</li>
            <li>@Html.ActionLink("Setup account", "CreateAccount", "Install")</li>
        </ol>
    </div>
</div>

YANBE/Views/Install/Settings.cshtml
@model YANBE.Models.SettingsModel

@{
    ViewBag.Title = "Apply settings";
}

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Settings", "Install", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.ConnectionString, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.ConnectionString, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ConnectionString)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>