YANBE/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Core.Domain;
using EFConvention;
using WebGrease.Css.Extensions;
using YANBE.Library;
using YANBE.Models;

namespace YANBE.Controllers
{
    public class PostController : Controller
    {
        private DbContext _context;
        private Markdown _markdown;
        
        public PostController(DbContext context, Markdown markdown)
        {
            _context = context;
            _markdown = markdown;
        
        }

        public ActionResult Index()
        {
            return View();
        }

        public string Markdown(string source, bool external = true)
        {
            return _markdown.Transform(source, external);
        }

        public ActionResult View(int id, string slug = "")
        {
            var model = _context.Set<Post>().Include(x => x.Tags).FirstOrDefault(x => x.Id == id);
            if (model == null) return RedirectToAction("Index", "Home");
            
            model.Body = Markdown(model.Body, false);
            return View(model);
        }

        [Authorize]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(PostModel model)
        {
            if (ModelState.IsValid)
            {
                var post = Mapper.Map<Post>(model);
                _context.Set<Post>().Add(post);
                _context.SaveChanges();
                return RedirectToAction("View", new {id = post.Id, slug = post.TitleSlug});
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var model = _context.Set<Post>().Include(x => x.Tags).FirstOrDefault(x => x.Id == id);
            if (model == null) return RedirectToAction("Index", "Home");
            return View(Mapper.Map<PostEditModel>(model));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(PostEditModel model)
        {
            if (ModelState.IsValid)
            {
                var foundPost = _context.Set<Post>().Include(x => x.Tags).FirstOrDefault(x => x.Id == model.Id);
                if (foundPost == null) return RedirectToAction("Index", "Home");
                
                Mapper.Map(model, foundPost);
                _context.SaveChanges();
                return RedirectToAction("Edit", new { id = model.Id });
            }
            return View(model);
        }
    }
}

YANBE/Controllers/TagsController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Core.Domain;
using EFConvention;
using YANBE.Models;

namespace YANBE.Controllers
{
    public class TagsController : Controller
    {
        private DbContext _context;

        public TagsController(DbContext context)
        {
            _context = context;
        }

        public ActionResult Details(string id)
        {
            id = id.Replace("-", " ");
            var model = new TagsModel()
            {
                Posts = _context.Set<Post>().Where(x => x.Tags.Any(c => c.Name == id)).ToList(),
                Tag = id
            };
            
            return View(model);
        }
    }
}

YANBE/Views/Post/Create.cshtml
@model YANBE.Models.PostModel

@{
    ViewBag.Title = "Create post";
}

<h2>Create post</h2>

<div class="row">
    <div class="col-md-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Title)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Tags, new { @class = "col-md-2 control-label" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Tags, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Tags)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @Html.TextAreaFor(m => m.Body, 60, 80, new { @class = "form-control2", style = "max-width: 100%; font-family:monospace" })
                        @Html.ValidationMessageFor(m => m.Body)
                    </div>
                    <div class="col-md-6">
                        <div id="preview" class="markdown-body"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/markitup")
    <script type="text/javascript">
        var requiresUpdate = false;
        $(function() {
            //$('#Body').markItUp(mySettings);
            $('#Body').bind('input propertychange', function() {
                requiresUpdate = true;
            });
            $(document).delegate('#Body', 'keydown', function (e) {
                var keyCode = e.keyCode || e.which;

                if (keyCode == 9) {
                    e.preventDefault();
                    var start = $(this).get(0).selectionStart;
                    var end = $(this).get(0).selectionEnd;

                    // set textarea value to: text before caret + tab + text after caret
                    $(this).val($(this).val().substring(0, start)
                                + "\t"
                                + $(this).val().substring(end));

                    // put caret at right position again
                    $(this).get(0).selectionStart =
                    $(this).get(0).selectionEnd = start + 1;
                }
            });
        });
        window.setInterval(function () {
            if (!requiresUpdate) return;
            $.post('@Url.Action("Markdown")', { source: encodeURIComponent($('#Body').val()) }, function(data) {
                $('#preview').html(data);
            });
            requiresUpdate = false;
        }, 1000);

    </script>
}

YANBE/Views/Post/Edit.cshtml
@model YANBE.Models.PostEditModel

@{
    ViewBag.Title = "Edit post";
    
}


<h2>Create post</h2>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.Id)
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                    <div class="col-md-12">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(m => m.Tags, new { @class = "col-md-2 control-label" })
                    <div class="col-md-12">
                        @Html.TextBoxFor(m => m.Tags, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Tags)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    @Html.TextAreaFor(m => m.Body, 60, 80, new { @class = "form-control2", style = "max-width: 100%; font-family:monospace" })
                    @Html.ValidationMessageFor(m => m.Body)
                </div>
                <div class="col-md-6">
                    <div id="preview" class="markdown-body"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/markitup")
    <script type="text/javascript">
        var requiresUpdate = false;
        $(function() {
            //$('#Body').markItUp(mySettings);
            $('#Body').bind('input propertychange', function() {
                requiresUpdate = true;
            });
            $(document).delegate('#Body', 'keydown', function (e) {
                var keyCode = e.keyCode || e.which;

                if (keyCode == 9) {
                    e.preventDefault();
                    var start = $(this).get(0).selectionStart;
                    var end = $(this).get(0).selectionEnd;

                    // set textarea value to: text before caret + tab + text after caret
                    $(this).val($(this).val().substring(0, start)
                                + "\t"
                                + $(this).val().substring(end));

                    // put caret at right position again
                    $(this).get(0).selectionStart =
                    $(this).get(0).selectionEnd = start + 1;
                }
            });
        });
        window.setInterval(function () {
            if (!requiresUpdate) return;
            $.post('@Url.Action("Markdown")', { source: encodeURIComponent($('#Body').val()) }, function(data) {
                $('#preview').html(data);
            });
            requiresUpdate = false;
        }, 1000);

    </script>
}

YANBE/Views/Post/View.cshtml
@using MarkdownSharp
@using YANBE.Library
@model Core.Domain.Post

@{
    ViewBag.Title = Model.Title;
    var pStart = Model.Body.IndexOf("<p>", System.StringComparison.Ordinal);
    var pend = Model.Body.IndexOf("</p>", System.StringComparison.Ordinal);
    var pContents = Model.Body.Substring(pStart + 3, pend - pStart - 3);
}

@section meta
{
    <meta property="og:title" content="@Model.Title"/>
    <meta property="og:type" content="article" />
    <meta property="og:url" content="@Url.Action("View", "Post", new { Model.Id, slug = Model.TitleSlug }, Request.Url.Scheme)" />
    <meta property="og:description" content="@pContents" />
    <meta property="og:site_name" content="Nero's blog" />
}

@section header
{
    <script type="text/javascript">var switchTo5x = true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({ publisher: "389dabf0-7be8-425e-8205-8dded2c4c406", doNotHash: false, doNotCopy: false, hashAddressBar: true });</script>
}

<div class="row">
    <div class="col-md-12">
        <h2>@Model.Title</h2>
        @Html.Raw(Model.Body)
    </div>  
</div>
@if (Model.Tags != null && Model.Tags.Any())
{
    <div class="row">
        <div class="col-md-12">
            Tags:
            @{
                var list = Model.Tags.Select(tag => Html.ActionLink(tag.Name, "Details", "Tags", new { id = tag.Name }, null)).ToList();
                @Html.Raw(string.Join(", ", list))
            }
        </div>
    </div>
}
<hr />
<div class="row" id="sharethis">
    <div class="col-md-12">
        @{
            var shares = new Dictionary<string, string>()
        {
            { "st_sharethis_hcount", "ShareThis" },
            { "st_facebook_hcount", "Facebook" },
            { "st_twitter_hcount", "Tweet" },
            { "st_googleplus_hcount", "Google +" },
            { "st_email_hcount", "Email" },
            { "st_linkedin_hcount", "LinkedIn" },
        };
            foreach (var share in shares)
            {
                <span class="@share.Key" displaytext="@share.Value" st_url="@Url.Action("View", "Post", new { Model.Id, slug = Model.TitleSlug }, Request.Url.Scheme)" st_title="@Model.Title" st_summary="@pContents"></span>
            }
        }
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="disqus_thread"></div>

        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'nerosule'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function () {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
</div>